import { CropNPK } from './types';

export const PUNJAB_CROPS: CropNPK[] = [
  // --- CROPS ---
  { name: "Rice (Paddy)", n: 120, p: 60, k: 40, category: "Crops", description: "Standard high-yield variety requirement." },
  { name: "Wheat (HD-2967)", n: 120, p: 60, k: 40, category: "Crops", description: "Most common wheat variety in Punjab." },
  { name: "Maize (Corn)", n: 150, p: 75, k: 50, category: "Crops", description: "Hybrid maize for high protein yield." },
  { name: "Sugarcane", n: 250, p: 100, k: 125, category: "Crops", description: "Long duration crop with high nutrient demand." },
  { name: "Cotton (Bt)", n: 100, p: 50, k: 50, category: "Crops", description: "Requires careful soil management for boll quality." },
  { name: "Mustard (Raya)", n: 80, p: 40, k: 40, category: "Crops", description: "Oilseed crop, sensitive to sulfur and nitrogen." },
  { name: "Sunflower", n: 60, p: 90, k: 60, category: "Crops", description: "Moderate feeder, sensitive to phosphorus." },
  { name: "Barley", n: 60, p: 30, k: 20, category: "Crops", description: "Less intensive than wheat." },
  { name: "Bajra (Pearl Millet)", n: 80, p: 40, k: 40, category: "Crops", description: "Hardy cereal for dry regions." },
  { name: "Moong (Green Gram)", n: 20, p: 40, k: 20, category: "Crops", description: "Nitrogen-fixing legume." },
  { name: "Mash (Black Gram)", n: 20, p: 40, k: 20, category: "Crops", description: "Pulses for soil improvement." },
  { name: "Groundnut", n: 25, p: 50, k: 50, category: "Crops", description: "Oilseed with high phosphorus requirement." },
  { name: "Chickpea (Chana)", n: 20, p: 40, k: 20, category: "Crops", description: "Winter pulse crop." },
  { name: "Lentil (Masur)", n: 20, p: 40, k: 20, category: "Crops", description: "Small-seeded pulse." },
  { name: "Pigeon Pea (Arhar)", n: 30, p: 60, k: 30, category: "Crops", description: "Long duration pulse." },
  { name: "Soybean", n: 30, p: 80, k: 40, category: "Crops", description: "High protein oilseed." },
  { name: "Sesame (Til)", n: 40, p: 20, k: 20, category: "Crops", description: "Small oilseed crop." },
  { name: "Toria", n: 60, p: 30, k: 30, category: "Crops", description: "Short duration oilseed." },
  { name: "Jowar (Sorghum)", n: 100, p: 50, k: 40, category: "Crops", description: "Fodder and grain crop." },
  { name: "Guara", n: 20, p: 40, k: 20, category: "Crops", description: "Industrial gum source and fodder." },
  { name: "Oats", n: 80, p: 40, k: 40, category: "Crops", description: "Excellent fodder crop." },
  { name: "Berseem", n: 25, p: 75, k: 30, category: "Crops", description: "Primary winter fodder in Punjab." },
  { name: "Lucerne (Alfalfa)", n: 20, p: 80, k: 40, category: "Crops", description: "High protein perennial fodder." },

  // --- VEGETABLES ---
  { name: "Potato", n: 180, p: 80, k: 120, category: "Vegetables", description: "High potassium requirement for tubers." },
  { name: "Tomato", n: 100, p: 60, k: 60, category: "Vegetables", description: "Fruit quality depends on balanced NPK." },
  { name: "Onion", n: 100, p: 50, k: 50, category: "Vegetables", description: "Essential for bulb size and storage." },
  { name: "Cauliflower", n: 120, p: 60, k: 60, category: "Vegetables", description: "Nitrogen intensive for curd development." },
  { name: "Cabbage", n: 150, p: 80, k: 80, category: "Vegetables", description: "Requires uniform nutrient supply." },
  { name: "Peas", n: 40, p: 60, k: 40, category: "Vegetables", description: "Nitrogen fixing but needs starter N." },
  { name: "Carrot", n: 80, p: 40, k: 80, category: "Vegetables", description: "Potassium helps in root quality." },
  { name: "Radish", n: 50, p: 25, k: 50, category: "Vegetables", description: "Fast growing root vegetable." },
  { name: "Garlic", n: 100, p: 50, k: 50, category: "Vegetables", description: "Sulfur also crucial for aroma." },
  { name: "Chilli", n: 100, p: 60, k: 60, category: "Vegetables", description: "Pungency and yield tied to K." },
  { name: "Okra (Bhindi)", n: 100, p: 50, k: 50, category: "Vegetables", description: "Summer vegetable, needs steady N." },
  { name: "Bottle Gourd", n: 60, p: 40, k: 40, category: "Vegetables", description: "Vigorously growing vine." },
  { name: "Bitter Gourd", n: 60, p: 40, k: 40, category: "Vegetables", description: "Medicinal and nutritional value." },
  { name: "Brinjal (Eggplant)", n: 100, p: 60, k: 60, category: "Vegetables", description: "Heavy feeder for long duration." },
  { name: "Spinach (Palak)", n: 80, p: 40, k: 40, category: "Vegetables", description: "Leafy green, nitrogen intensive." },
  { name: "Ginger", n: 75, p: 50, k: 50, category: "Vegetables", description: "Shade loving rhizome." },
  { name: "Turmeric", n: 60, p: 50, k: 100, category: "Vegetables", description: "High K for rhizome quality." },
  { name: "Cucumber", n: 50, p: 50, k: 50, category: "Vegetables", description: "High water and balanced nutrient needs." },
  { name: "Pumpkin", n: 60, p: 40, k: 40, category: "Vegetables", description: "Large fruit, needs organic matter." },
  { name: "Muskmelon", n: 80, p: 40, k: 40, category: "Vegetables", description: "Critical for sweetness." },
  { name: "Watermelon", n: 80, p: 40, k: 40, category: "Vegetables", description: "High moisture and nutrient demand." },
  { name: "Capsicum", n: 100, p: 60, k: 60, category: "Vegetables", description: "Sensitive to micronutrients." },
  { name: "Broccoli", n: 120, p: 60, k: 60, category: "Vegetables", description: "Exotic health vegetable." },
  { name: "Lettuce", n: 60, p: 30, k: 30, category: "Vegetables", description: "Fast-cycle leafy crop." },

  // --- FRUITS ---
  { name: "Kinnow (Mandarin)", n: 400, p: 200, k: 200, category: "Fruits", description: "Pride of Punjab; requirements for mature tree/yr." },
  { name: "Guava", n: 300, p: 150, k: 150, category: "Fruits", description: "Hardy fruit tree; NPK for mature tree." },
  { name: "Mango", n: 500, p: 250, k: 250, category: "Fruits", description: "King of fruits; needs post-harvest N." },
  { name: "Grapes", n: 200, p: 100, k: 300, category: "Fruits", description: "Potassium intensive for sugar content." },
  { name: "Ber (Jujube)", n: 200, p: 100, k: 100, category: "Fruits", description: "Arid fruit, requires pruning and fert." },
  { name: "Pear", n: 300, p: 150, k: 150, category: "Fruits", description: "Suitable for central Punjab." },
  { name: "Peach", n: 250, p: 125, k: 125, category: "Fruits", description: "Short-lived but high yield." },
  { name: "Plum", n: 250, p: 125, k: 125, category: "Fruits", description: "Cooling and nutritious fruit." },
  { name: "Pomegranate", n: 400, p: 200, k: 200, category: "Fruits", description: "High value arid fruit." },
  { name: "Banana", n: 200, p: 50, k: 300, category: "Fruits", description: "Potassium giant for mass/flesh." },
  { name: "Papaya", n: 250, p: 250, k: 500, category: "Fruits", description: "Fast growing, needs continuous fert." },
  { name: "Amla", n: 200, p: 100, k: 100, category: "Fruits", description: "Vitamin C rich hardy tree." },
  { name: "Litchi", n: 400, p: 200, k: 200, category: "Fruits", description: "Specific to Gurdaspur/Pathankot belt." },
  { name: "Strawberry", n: 80, p: 40, k: 80, category: "Fruits", description: "Modern high-value berry." },
  { name: "Loquat", n: 200, p: 100, k: 100, category: "Fruits", description: "Spring ripening fruit." },
  { name: "Phalsa", n: 100, p: 50, k: 50, category: "Fruits", description: "Traditional small berry fruit." },
  { name: "Jamun", n: 300, p: 150, k: 150, category: "Fruits", description: "Nutritional summer fruit." },
  { name: "Custard Apple", n: 200, p: 100, k: 200, category: "Fruits", description: "Low maintenance subtropical fruit." },

  // --- TREES ---
  { name: "Eucalyptus", n: 100, p: 50, k: 50, category: "Trees", description: "Fast growing timber/pulp tree." },
  { name: "Poplar", n: 120, p: 60, k: 60, category: "Trees", description: "Agroforestry staple for plywood." },
  { name: "Neem", n: 50, p: 25, k: 25, category: "Trees", description: "Medicinal and insecticide properties." },
  { name: "Kikar (Acacia)", n: 30, p: 15, k: 15, category: "Trees", description: "Hard wood, nitrogen fixing." },
  { name: "Shisham", n: 40, p: 20, k: 20, category: "Trees", description: "Premium quality timber." },
  { name: "Bamboo", n: 150, p: 75, k: 75, category: "Trees", description: "Fastest growing biomass resource." },
  { name: "Willow", n: 80, p: 40, k: 40, category: "Trees", description: "Sports goods timber." },
  { name: "Teak", n: 60, p: 30, k: 30, category: "Trees", description: "High value timber, slow growing." },
  { name: "Sandalwood", n: 40, p: 20, k: 20, category: "Trees", description: "Semi-parasitic high value tree." },
  { name: "Moringa", n: 50, p: 30, k: 30, category: "Trees", description: "Oily seed and nutritious leaves." },
  { name: "Banyan", n: 20, p: 10, k: 10, category: "Trees", description: "Religious and shade tree." },
  { name: "Peepal", n: 20, p: 10, k: 10, category: "Trees", description: "Ecological giant, oxygen source." },
  { name: "Simbal (Silk Cotton)", n: 40, p: 20, k: 20, category: "Trees", description: "Large tree for soft wood." },
  { name: "Bakain", n: 30, p: 15, k: 15, category: "Trees", description: "Fast growing shade tree." },
  { name: "Khair", n: 20, p: 10, k: 10, category: "Trees", description: "Cutch and Katha source." },
  { name: "Silver Oak", n: 40, p: 20, k: 20, category: "Trees", description: "Shade for tea/coffee or ornamental." },
  { name: "Gulmohar", n: 30, p: 15, k: 15, category: "Trees", description: "Ornamental flowering tree." },
  { name: "Amaltas", n: 30, p: 15, k: 15, category: "Trees", description: "Golden shower tree." },
  { name: "Tali (Sissoo)", n: 40, p: 20, k: 20, category: "Trees", description: "Punjab's state tree." },
  { name: "Arjun", n: 40, p: 20, k: 20, category: "Trees", description: "Medicinal bark and timber." },
  { name: "Bahera", n: 30, p: 15, k: 15, category: "Trees", description: "Triphala ingredient." },
  { name: "Harad", n: 30, p: 15, k: 15, category: "Trees", description: "Important ayurvedic tree." },
  { name: "Bel", n: 50, p: 25, k: 50, category: "Trees", description: "Nutritious fruit and medicinal." },
  { name: "Lemon", n: 100, p: 50, k: 50, category: "Trees", description: "Garden staple citrus." },
  { name: "Pine (Chir)", n: 40, p: 20, k: 20, category: "Trees", description: "Resin and timber from hills." },
  { name: "Cedar (Deodar)", n: 20, p: 10, k: 10, category: "Trees", description: "Holy timber, high altitudes." },
  { name: "Maple", n: 30, p: 15, k: 15, category: "Trees", description: "Cool climate hills tree." },
  { name: "Walnut", n: 100, p: 50, k: 50, category: "Trees", description: "Premium nut and timber." },
  { name: "Apple", n: 120, p: 60, k: 120, category: "Trees", description: "High altitude Punjab belts." },
  { name: "Apricot", n: 80, p: 40, k: 80, category: "Trees", description: "Stone fruit from hills." },
  { name: "Cherry", n: 100, p: 50, k: 100, category: "Trees", description: "Temperate fruit tree." },
  { name: "Fig", n: 50, p: 25, k: 50, category: "Trees", description: "Traditional fruit tree." },
  { name: "Mulberry (Tut)", n: 60, p: 30, k: 30, category: "Trees", description: "Sericulture and fruit." },
  { name: "Hibiscus", n: 20, p: 20, k: 20, category: "Trees", description: "Flowering shrub/small tree." },
  { name: "Ixora", n: 20, p: 10, k: 10, category: "Trees", description: "Ornamental garden plant." },
  { name: "Bougainvillea", n: 10, p: 10, k: 10, category: "Trees", description: "Hardy ornamental climber." },
];
